### PR TITLE
Switch to symbolic icons in toolbar and buttons

### PR DESCRIPTION
**Pull request by clefebvre**
Remove icons from dialog buttons (consistent with GTK3 apps)
Switch to symbolic icon names in toolbar to improve support
for HiDPI and dark themes.

### CODE REVIEW

**Comment by clefebvre** [comment]
I marked the PR as WIP for now.. I spotted a few png images which weren't fix in the first commit.

**Comment by clefebvre** [comment]
Here's an overview of what's wrong:

timeshift_001

This is in HiDPI mode with a dark theme.

create snapshot_002

Some icons look blurry (open-menu and the assistant icon).

Some icons are dark and do not look good in dark themes.

Last but not least.. there's an inconsistent use of icons within buttons within button boxes.

To fix this we switch to symbolic icon names. Given a symbolic icon name, GTK is able to scale the icon properly thus giving us good HiDPI support. It also generates the right tint for it, making it look dark on top of light themes or light on top of dark themes, so the icon looks good for everybody no matter what GTK theme they're using.

timeshift_003

create snapshot_004

timeshift_005

**Comment by clefebvre** [comment]
From an aesthetic point of view I know it's a little hard for some people to accept going towards symbolic icons. We've been used to fullcolor icons for so long with GTK2, and back in those days it was the trend to overload apps with icons in menubars and button boxes.

Once you get used to it, it brings many benefits though.

In this PR I just switched icons to available icon names. If you want to go further with this I would recommend to design our own timeshift-assistant-symbolic.svg and replace the emblem I used in here.

**Comment by teejee2008** [comment]
Looks good. I'll try out these changes and merge it.

**Pull request merged**
