### PR TITLE
Workaround for Docker mounting rootfs on /var/lib/docker/plugins

### PR DESCRIPTION
**Pull request by bazoocaze**
Hi, friend
Please kindly appreciate this simply PR and merge it if you feel it will help some users of your great utility.
Regards,
Jose F

Related to #189 and #227

### CODE REVIEW

**Comment by DariusQuintus** [comment]
I suggest using /var/lib/docker, because it's either aufs/ or timeshift/ or plugins/

**Comment by bazoocaze** [comment]
Updated directory to `/var/lib/docker`

**Comment by Redsandro** [comment]
My docker directory is actually at `/mnt/zfs/docker` on my desktop and `/home/docker` on my laptop.

You might want to change `/var/lib/docker` to just `/docker` as in `contains("/docker")`.

**Comment by bazoocaze** [comment]
Changed to `/docker`

**Comment by bazoocaze** [comment]
The correct solution for this is to patch #227. But, the real question is:
>How to determine if a mount point is a bind-mount point? 

If we can determine that, I can make a real patch (instead of this work-around).

**Comment by teejee2008** [comment]
PR is merged. Changes are included in v18.8.

**Pull request merged**
